<template>
  <div class="container mx-auto">
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore expedita magni aliquid modi quis! Similique, aliquam rerum, quibusdam delectus culpa eius amet vero iusto quos assumenda cupiditate consectetur temporibus quaerat aut veniam in blanditiis. Mollitia ea quaerat in dignissimos perspiciatis! Modi similique autem nobis. Quidem fugiat optio ut, at cumque unde quis alias sit, iusto culpa corrupti cupiditate ducimus. Iure quae perferendis dolorem accusantium enim eveniet officiis nobis quam in vitae. Tempora autem labore nisi assumenda quam natus, ea iste quos maxime nemo rerum qui vel! Possimus cum, omnis, minima quisquam cumque adipisci iusto libero quod, fugit recusandae neque est optio reprehenderit ea quos ipsum itaque officia. Nihil, molestias possimus optio ex asperiores quasi inventore sunt pariatur commodi ipsum repellat, distinctio accusantium quibusdam doloribus magni veritatis in blanditiis maiores dolore aut minima ipsam. Dignissimos praesentium odio nam ipsum nostrum est veritatis sint. Incidunt quas accusamus quidem quia eum consequatur laudantium, illo libero et voluptates cum. Nulla optio soluta asperiores ipsam inventore provident incidunt ab dicta iure, eveniet reprehenderit maiores necessitatibus exercitationem ducimus atque quod id. Officiis nisi iusto dignissimos, repellendus asperiores neque velit molestias fugiat et ut sequi eius rerum delectus? Ducimus ad tenetur adipisci, voluptatum dolore omnis expedita ex!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore expedita magni aliquid modi quis! Similique, aliquam rerum, quibusdam delectus culpa eius amet vero iusto quos assumenda cupiditate consectetur temporibus quaerat aut veniam in blanditiis. Mollitia ea quaerat in dignissimos perspiciatis! Modi similique autem nobis. Quidem fugiat optio ut, at cumque unde quis alias sit, iusto culpa corrupti cupiditate ducimus. Iure quae perferendis dolorem accusantium enim eveniet officiis nobis quam in vitae. Tempora autem labore nisi assumenda quam natus, ea iste quos maxime nemo rerum qui vel! Possimus cum, omnis, minima quisquam cumque adipisci iusto libero quod, fugit recusandae neque est optio reprehenderit ea quos ipsum itaque officia. Nihil, molestias possimus optio ex asperiores quasi inventore sunt pariatur commodi ipsum repellat, distinctio accusantium quibusdam doloribus magni veritatis in blanditiis maiores dolore aut minima ipsam. Dignissimos praesentium odio nam ipsum nostrum est veritatis sint. Incidunt quas accusamus quidem quia eum consequatur laudantium, illo libero et voluptates cum. Nulla optio soluta asperiores ipsam inventore provident incidunt ab dicta iure, eveniet reprehenderit maiores necessitatibus exercitationem ducimus atque quod id. Officiis nisi iusto dignissimos, repellendus asperiores neque velit molestias fugiat et ut sequi eius rerum delectus? Ducimus ad tenetur adipisci, voluptatum dolore omnis expedita ex!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore expedita magni aliquid modi quis! Similique, aliquam rerum, quibusdam delectus culpa eius amet vero iusto quos assumenda cupiditate consectetur temporibus quaerat aut veniam in blanditiis. Mollitia ea quaerat in dignissimos perspiciatis! Modi similique autem nobis. Quidem fugiat optio ut, at cumque unde quis alias sit, iusto culpa corrupti cupiditate ducimus. Iure quae perferendis dolorem accusantium enim eveniet officiis nobis quam in vitae. Tempora autem labore nisi assumenda quam natus, ea iste quos maxime nemo rerum qui vel! Possimus cum, omnis, minima quisquam cumque adipisci iusto libero quod, fugit recusandae neque est optio reprehenderit ea quos ipsum itaque officia. Nihil, molestias possimus optio ex asperiores quasi inventore sunt pariatur commodi ipsum repellat, distinctio accusantium quibusdam doloribus magni veritatis in blanditiis maiores dolore aut minima ipsam. Dignissimos praesentium odio nam ipsum nostrum est veritatis sint. Incidunt quas accusamus quidem quia eum consequatur laudantium, illo libero et voluptates cum. Nulla optio soluta asperiores ipsam inventore provident incidunt ab dicta iure, eveniet reprehenderit maiores necessitatibus exercitationem ducimus atque quod id. Officiis nisi iusto dignissimos, repellendus asperiores neque velit molestias fugiat et ut sequi eius rerum delectus? Ducimus ad tenetur adipisci, voluptatum dolore omnis expedita ex!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore expedita magni aliquid modi quis! Similique, aliquam rerum, quibusdam delectus culpa eius amet vero iusto quos assumenda cupiditate consectetur temporibus quaerat aut veniam in blanditiis. Mollitia ea quaerat in dignissimos perspiciatis! Modi similique autem nobis. Quidem fugiat optio ut, at cumque unde quis alias sit, iusto culpa corrupti cupiditate ducimus. Iure quae perferendis dolorem accusantium enim eveniet officiis nobis quam in vitae. Tempora autem labore nisi assumenda quam natus, ea iste quos maxime nemo rerum qui vel! Possimus cum, omnis, minima quisquam cumque adipisci iusto libero quod, fugit recusandae neque est optio reprehenderit ea quos ipsum itaque officia. Nihil, molestias possimus optio ex asperiores quasi inventore sunt pariatur commodi ipsum repellat, distinctio accusantium quibusdam doloribus magni veritatis in blanditiis maiores dolore aut minima ipsam. Dignissimos praesentium odio nam ipsum nostrum est veritatis sint. Incidunt quas accusamus quidem quia eum consequatur laudantium, illo libero et voluptates cum. Nulla optio soluta asperiores ipsam inventore provident incidunt ab dicta iure, eveniet reprehenderit maiores necessitatibus exercitationem ducimus atque quod id. Officiis nisi iusto dignissimos, repellendus asperiores neque velit molestias fugiat et ut sequi eius rerum delectus? Ducimus ad tenetur adipisci, voluptatum dolore omnis expedita ex!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore expedita magni aliquid modi quis! Similique, aliquam rerum, quibusdam delectus culpa eius amet vero iusto quos assumenda cupiditate consectetur temporibus quaerat aut veniam in blanditiis. Mollitia ea quaerat in dignissimos perspiciatis! Modi similique autem nobis. Quidem fugiat optio ut, at cumque unde quis alias sit, iusto culpa corrupti cupiditate ducimus. Iure quae perferendis dolorem accusantium enim eveniet officiis nobis quam in vitae. Tempora autem labore nisi assumenda quam natus, ea iste quos maxime nemo rerum qui vel! Possimus cum, omnis, minima quisquam cumque adipisci iusto libero quod, fugit recusandae neque est optio reprehenderit ea quos ipsum itaque officia. Nihil, molestias possimus optio ex asperiores quasi inventore sunt pariatur commodi ipsum repellat, distinctio accusantium quibusdam doloribus magni veritatis in blanditiis maiores dolore aut minima ipsam. Dignissimos praesentium odio nam ipsum nostrum est veritatis sint. Incidunt quas accusamus quidem quia eum consequatur laudantium, illo libero et voluptates cum. Nulla optio soluta asperiores ipsam inventore provident incidunt ab dicta iure, eveniet reprehenderit maiores necessitatibus exercitationem ducimus atque quod id. Officiis nisi iusto dignissimos, repellendus asperiores neque velit molestias fugiat et ut sequi eius rerum delectus? Ducimus ad tenetur adipisci, voluptatum dolore omnis expedita ex!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore expedita magni aliquid modi quis! Similique, aliquam rerum, quibusdam delectus culpa eius amet vero iusto quos assumenda cupiditate consectetur temporibus quaerat aut veniam in blanditiis. Mollitia ea quaerat in dignissimos perspiciatis! Modi similique autem nobis. Quidem fugiat optio ut, at cumque unde quis alias sit, iusto culpa corrupti cupiditate ducimus. Iure quae perferendis dolorem accusantium enim eveniet officiis nobis quam in vitae. Tempora autem labore nisi assumenda quam natus, ea iste quos maxime nemo rerum qui vel! Possimus cum, omnis, minima quisquam cumque adipisci iusto libero quod, fugit recusandae neque est optio reprehenderit ea quos ipsum itaque officia. Nihil, molestias possimus optio ex asperiores quasi inventore sunt pariatur commodi ipsum repellat, distinctio accusantium quibusdam doloribus magni veritatis in blanditiis maiores dolore aut minima ipsam. Dignissimos praesentium odio nam ipsum nostrum est veritatis sint. Incidunt quas accusamus quidem quia eum consequatur laudantium, illo libero et voluptates cum. Nulla optio soluta asperiores ipsam inventore provident incidunt ab dicta iure, eveniet reprehenderit maiores necessitatibus exercitationem ducimus atque quod id. Officiis nisi iusto dignissimos, repellendus asperiores neque velit molestias fugiat et ut sequi eius rerum delectus? Ducimus ad tenetur adipisci, voluptatum dolore omnis expedita ex!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore expedita magni aliquid modi quis! Similique, aliquam rerum, quibusdam delectus culpa eius amet vero iusto quos assumenda cupiditate consectetur temporibus quaerat aut veniam in blanditiis. Mollitia ea quaerat in dignissimos perspiciatis! Modi similique autem nobis. Quidem fugiat optio ut, at cumque unde quis alias sit, iusto culpa corrupti cupiditate ducimus. Iure quae perferendis dolorem accusantium enim eveniet officiis nobis quam in vitae. Tempora autem labore nisi assumenda quam natus, ea iste quos maxime nemo rerum qui vel! Possimus cum, omnis, minima quisquam cumque adipisci iusto libero quod, fugit recusandae neque est optio reprehenderit ea quos ipsum itaque officia. Nihil, molestias possimus optio ex asperiores quasi inventore sunt pariatur commodi ipsum repellat, distinctio accusantium quibusdam doloribus magni veritatis in blanditiis maiores dolore aut minima ipsam. Dignissimos praesentium odio nam ipsum nostrum est veritatis sint. Incidunt quas accusamus quidem quia eum consequatur laudantium, illo libero et voluptates cum. Nulla optio soluta asperiores ipsam inventore provident incidunt ab dicta iure, eveniet reprehenderit maiores necessitatibus exercitationem ducimus atque quod id. Officiis nisi iusto dignissimos, repellendus asperiores neque velit molestias fugiat et ut sequi eius rerum delectus? Ducimus ad tenetur adipisci, voluptatum dolore omnis expedita ex!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore expedita magni aliquid modi quis! Similique, aliquam rerum, quibusdam delectus culpa eius amet vero iusto quos assumenda cupiditate consectetur temporibus quaerat aut veniam in blanditiis. Mollitia ea quaerat in dignissimos perspiciatis! Modi similique autem nobis. Quidem fugiat optio ut, at cumque unde quis alias sit, iusto culpa corrupti cupiditate ducimus. Iure quae perferendis dolorem accusantium enim eveniet officiis nobis quam in vitae. Tempora autem labore nisi assumenda quam natus, ea iste quos maxime nemo rerum qui vel! Possimus cum, omnis, minima quisquam cumque adipisci iusto libero quod, fugit recusandae neque est optio reprehenderit ea quos ipsum itaque officia. Nihil, molestias possimus optio ex asperiores quasi inventore sunt pariatur commodi ipsum repellat, distinctio accusantium quibusdam doloribus magni veritatis in blanditiis maiores dolore aut minima ipsam. Dignissimos praesentium odio nam ipsum nostrum est veritatis sint. Incidunt quas accusamus quidem quia eum consequatur laudantium, illo libero et voluptates cum. Nulla optio soluta asperiores ipsam inventore provident incidunt ab dicta iure, eveniet reprehenderit maiores necessitatibus exercitationem ducimus atque quod id. Officiis nisi iusto dignissimos, repellendus asperiores neque velit molestias fugiat et ut sequi eius rerum delectus? Ducimus ad tenetur adipisci, voluptatum dolore omnis expedita ex!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore expedita magni aliquid modi quis! Similique, aliquam rerum, quibusdam delectus culpa eius amet vero iusto quos assumenda cupiditate consectetur temporibus quaerat aut veniam in blanditiis. Mollitia ea quaerat in dignissimos perspiciatis! Modi similique autem nobis. Quidem fugiat optio ut, at cumque unde quis alias sit, iusto culpa corrupti cupiditate ducimus. Iure quae perferendis dolorem accusantium enim eveniet officiis nobis quam in vitae. Tempora autem labore nisi assumenda quam natus, ea iste quos maxime nemo rerum qui vel! Possimus cum, omnis, minima quisquam cumque adipisci iusto libero quod, fugit recusandae neque est optio reprehenderit ea quos ipsum itaque officia. Nihil, molestias possimus optio ex asperiores quasi inventore sunt pariatur commodi ipsum repellat, distinctio accusantium quibusdam doloribus magni veritatis in blanditiis maiores dolore aut minima ipsam. Dignissimos praesentium odio nam ipsum nostrum est veritatis sint. Incidunt quas accusamus quidem quia eum consequatur laudantium, illo libero et voluptates cum. Nulla optio soluta asperiores ipsam inventore provident incidunt ab dicta iure, eveniet reprehenderit maiores necessitatibus exercitationem ducimus atque quod id. Officiis nisi iusto dignissimos, repellendus asperiores neque velit molestias fugiat et ut sequi eius rerum delectus? Ducimus ad tenetur adipisci, voluptatum dolore omnis expedita ex!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore expedita magni aliquid modi quis! Similique, aliquam rerum, quibusdam delectus culpa eius amet vero iusto quos assumenda cupiditate consectetur temporibus quaerat aut veniam in blanditiis. Mollitia ea quaerat in dignissimos perspiciatis! Modi similique autem nobis. Quidem fugiat optio ut, at cumque unde quis alias sit, iusto culpa corrupti cupiditate ducimus. Iure quae perferendis dolorem accusantium enim eveniet officiis nobis quam in vitae. Tempora autem labore nisi assumenda quam natus, ea iste quos maxime nemo rerum qui vel! Possimus cum, omnis, minima quisquam cumque adipisci iusto libero quod, fugit recusandae neque est optio reprehenderit ea quos ipsum itaque officia. Nihil, molestias possimus optio ex asperiores quasi inventore sunt pariatur commodi ipsum repellat, distinctio accusantium quibusdam doloribus magni veritatis in blanditiis maiores dolore aut minima ipsam. Dignissimos praesentium odio nam ipsum nostrum est veritatis sint. Incidunt quas accusamus quidem quia eum consequatur laudantium, illo libero et voluptates cum. Nulla optio soluta asperiores ipsam inventore provident incidunt ab dicta iure, eveniet reprehenderit maiores necessitatibus exercitationem ducimus atque quod id. Officiis nisi iusto dignissimos, repellendus asperiores neque velit molestias fugiat et ut sequi eius rerum delectus? Ducimus ad tenetur adipisci, voluptatum dolore omnis expedita ex!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore expedita magni aliquid modi quis! Similique, aliquam rerum, quibusdam delectus culpa eius amet vero iusto quos assumenda cupiditate consectetur temporibus quaerat aut veniam in blanditiis. Mollitia ea quaerat in dignissimos perspiciatis! Modi similique autem nobis. Quidem fugiat optio ut, at cumque unde quis alias sit, iusto culpa corrupti cupiditate ducimus. Iure quae perferendis dolorem accusantium enim eveniet officiis nobis quam in vitae. Tempora autem labore nisi assumenda quam natus, ea iste quos maxime nemo rerum qui vel! Possimus cum, omnis, minima quisquam cumque adipisci iusto libero quod, fugit recusandae neque est optio reprehenderit ea quos ipsum itaque officia. Nihil, molestias possimus optio ex asperiores quasi inventore sunt pariatur commodi ipsum repellat, distinctio accusantium quibusdam doloribus magni veritatis in blanditiis maiores dolore aut minima ipsam. Dignissimos praesentium odio nam ipsum nostrum est veritatis sint. Incidunt quas accusamus quidem quia eum consequatur laudantium, illo libero et voluptates cum. Nulla optio soluta asperiores ipsam inventore provident incidunt ab dicta iure, eveniet reprehenderit maiores necessitatibus exercitationem ducimus atque quod id. Officiis nisi iusto dignissimos, repellendus asperiores neque velit molestias fugiat et ut sequi eius rerum delectus? Ducimus ad tenetur adipisci, voluptatum dolore omnis expedita ex!</p>
    <v-form @submit.prevent="searchRecipes" class="mb-6">
      <v-text-field
        v-model="query"
        label="Enter ingredients (e.g., chicken, tomato)"
        class="mb-4"
        outlined
      ></v-text-field>
      <v-btn color="blue" type="submit">Search</v-btn>
    </v-form>
    <v-container v-if="recipes.length" class="mt-6">
      <v-row>
        <v-col v-for="recipe in recipes" :key="recipe.id" cols="12" md="6" lg="4">
          <v-card>
            <v-img :src="recipe.image" :alt="recipe.title" height="200px"></v-img>
            <v-card-title>{{ recipe.title }}</v-card-title>
            <v-card-actions>
              <v-btn :to="`/recipe/${recipe.id}`" color="blue" outlined>View Details</v-btn>
            </v-card-actions>
          </v-card>
        </v-col>
      </v-row>
    </v-container>
    <p v-else class="text-gray-500">No recipes found. Try another search.</p>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  data() {
    return {
      query: 'meat',
      recipes: [],
    };
  },
  methods: {
    async searchRecipes() {
      const apiKey = process.env.VUE_APP_SPOONACULAR_API_KEY;
      const url = `https://api.spoonacular.com/recipes/complexSearch?query=${this.query}&number=10&apiKey=${apiKey}`;
      try {
        const response = await axios.get(url);
        this.recipes = response.data.results;
      } catch (error) {
        console.error('Error fetching recipes:', error);
      }
    },
  },
};
</script>